all:
	echo "Use clean only"

clean:
	rm -f *~
	rm -rf simulation/
	rm -rf db/
	rm -f *.bak
	rm -f *.summary
	rm -f *.rpt
	rm -f *.pin
	rm -f *.eqn
	rm -f *.qmsg
	rm -f *.smsg
	rm -f *.done
	rm -f *.html
	rm -f *.jpg
	rm -f *.cmp
	rm -f *.inst
	rm -f *.sof
	rm -f *.bsf
	rm -f *.dpf
	rm -f *.ppf
	rm -f *.pof
	rm -f *.jdi
	rm -rf nios_system_sim/
	rm -rf .sopc_builder/
	rm -f *.ptf
	rm -f *_ptf
	rm -f *.mif
	rm -f *log.txt
