all:
	echo "Use clean only"

clean:
	rm -f *~
	rm -rf simulation/
	rm -rf db/
	rm -f *.bak
	rm -f *.summary
	rm -f *.rpt
	rm -f *.cmp
	rm -f *.html
	rm -f *.jpg
	rm -f *.done
	rm -f *.eqn
	rm -f *.qmsg
	rm -f *.pin
	rm -f *.smsg
