# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "/home/user4/spring12/nyh2105/embedded/romeo-set/src/ifv.qpf"
set_global_assignment -name VHDL_FILE altera_europa_support.vhd
project_close