# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "/home/user4/spring12/lep2141/4840/romeo-set/src/ifmunit.qpf"
set_global_assignment -name VHDL_FILE altera_europa_support.vhd
project_close