obj/alt_lseek.o:  \
 /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/src/alt_lseek.c \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/unistd.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/sys/unistd.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/_ansi.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/newlib.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/sys/config.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/machine/ieeefp.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/sys/types.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/sys/_types.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/include/stddef.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/machine/types.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/sys/features.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/sys/alt_errno.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/errno.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/sys/errno.h \
  /opt/altera/altera7.2/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.1/../../../../nios2-elf/include/sys/reent.h \
  /opt/altera/altera7.2/ip/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/altera7.2/ip/nios2_ip/altera_nios2/HAL/inc/sys/alt_warning.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/priv/alt_file.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  system_description/system.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/altera7.2/ip/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/os/alt_sem.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/priv/alt_no_error.h \
  /opt/altera/altera7.2/nios2eds/components/altera_hal/HAL/inc/os/alt_syscall.h
